version: '3.7'

services:
  web:
    build:     
      context: .
      dockerfile: Dockerfile_local
    user: root
    command: /bin/sh -c "python manage.py collectstatic --noinput && gunicorn test_api.wsgi:application --bind 0.0.0.0:8000 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./web.env
    depends_on:
      - db
  db:
    image: postgres:12.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db.env
volumes:
  postgres_data: